adjust authors to be more neutral about ex comtravos
comtravo/comtravo.github.io pull request #37
Opened 2021-07-03 07:41 UTC by sebastianmika

2021-07-04 09:48 UTC, bhuvinth commented on about.md
> +                <h4>The Comtravo tech blog is written by many great minds. Not surprinsgly many of them are current or former Comtravo employees.</h4>
Just fixing a typo: 
```suggestion
                <h4>The Comtravo tech blog is written by many great minds. Not surprisingly many of them are current or former Comtravo employees.</h4>
```

2021-07-04 16:12 UTC, utvara commented
👍💪

2021-07-05 08:21 UTC, davidsbatista approved these changes
Looks good :)

2021-07-05 08:23 UTC, Puneeth-n requested changes

2021-07-05 08:23 UTC, Puneeth-n commented on _data/authors.yml
> +    role: Seasons CTO | Tech Aficionado
```suggestion
    role: Seasoned CTO | Tech Aficionado
```

2021-07-05 08:46 UTC, kristianmitk commented on _data/authors.yml
> +    role: Seasons CTO | Tech Aficionado
I was wondering if this was intended 😄 Like switching to ski instructor during winter season ⛷️

2021-07-05 08:57 UTC, utvara commented on _data/authors.yml
> +    role: Seasons CTO | Tech Aficionado
https://svdictionary.com/words/tech-aficionado

> A person who is insecure about their superficial knowledge in software, hardware and technology in general, but really wants to fit in. It's a description often used in online social blogging bios.

😂 I'm sooo happy I never wrote anything for the blog 😂

2021-07-05 09:01 UTC, davidsbatista commented on _data/authors.yml
> +    role: Seasons CTO | Tech Aficionado
how can I open a PR for `https://svdictionary.com/words/tech-aficionado` ?

2021-07-06 13:27 UTC, merged